config/routes.rb
Rails.application.routes.draw do



 devise_scope :user do
    get "welcome/:page" => "welcome#show", :as => 'welcome'

  unauthenticated  do
    root "welcome#home", as: :unauthenticated_root
  end
  authenticated do
    get "dashboard/:page" => "dashboard#show", :as => 'dashboard'
    root 'dashboard#dashboard', as: :authenticated_root
  end
  # get 'user/:username' => 'user#profile'
 end


devise_for :users, controllers: {
        sessions: 'users/sessions'
      }



get 'welcome/home'
get 'welcome/contact'
# get '/:username' => 'dashboard#profile'

# Ressources users || particulièrment dangereux
# doit etre changer pour seulement si super admin et faire un crud pour chaque utilisateur
# Proteger par un double mot de passe
# et doit etre une suppression soft / grosse suppression doit uniquement etre faire via console
# et demande ecrite de l utilisateur
# resources :users, :path => '', :only => [:show]
  resources :users

# devise_for :user 
# two lines below are needed for devise/controller
 
    

  scope shallow_path: "librairie" do
    resources :courses, :path => "librairie" do
    	resources :chapters, shallow: true
      put :edit, on: :member  
    end


    resources :chapters do 
        resources :lessons, shallow: true
    end
    resources :lessons

  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

 attr_reader :courses
 helper_method :courses




 @courses = Course.all

  # GET /courses
  # GET /courses.json

  # def to_param
  #  "#{id}-#{title}"
  # end


  def index
    @courses = Course.all
    # @courses = Course.scoped
  end


  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    authorize! :read, @course
 end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    authorize! :edit, @course 
        if request.get?
          @course = Course.find(params[:id])
          @chapters = @course.chapters
     elsif request.put?
          params[:order].each do |key,value|
          Chapter.find(value[:id]).update_attribute(:position,value[:position])
          flash.now[:alert] =   'suis dans la boucle.' 
        end
        flash.now[:alert] =   'en dehors' 
        render :nothing => true
      end
    
    end


# def sort
#     params[:order].each do |key,value|
#       Chapter.find(value[:id]).update_attribute(:position,value[:position])
#     end
#     render :nothing => true
#   end

# def sort
#   @course = Course.find(params[:id])
#   @course.chapters.each do | chapter |
#     chapter.position = params["course"].index(chapter.id.to_s)+1
#     chapter.save
#   end
# end

    
   #  respond_to do |format|
   #       format.html {render :layout => false} #add this line.
   # end
  # end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    authorize! :create, @course
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authorize! :destroy, @course 
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
    
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_id, :title, :description, :course_icon, :category, :level, :teacher, :learning_skills, :course_points)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
	
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :course_icon %><br>
    <%= f.text_field :course_icon %>
  </div>
  <div class="field">
  <%= f.input :category, label: :category, collection: ['néophyte','débutant','intermédiaire','avancé','expert'], selected: 'intermédiaire' %>

    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :learning_skills %><br>
    <%= f.text_area :learning_skills %>
  </div>
  <div class="field">
    <%= f.label :course_points %><br>
    <%= f.text_field :course_points %>
  </div>
  <div class="actions">
     <%= f.button :submit, "Sauvegarder les Modifications ? " %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="course-content">

  <!-- Lien Retour -->
  <div class="row">
    <!-- link_to '<i class="fi-arrow-left"></i> Retour'.html_safe, url_for(:back) -->
    <%= link_to '<i class="fi-arrow-left"></i> Retour Librairie'.html_safe, courses_path %>
  </div>
  <!-- Fin Lien Retour -->

  <!-- Bloc de Présentation Générale du Cours -->
  <div class="row presentation-cours-bloc">

    <!-- Icone du cours -->
    <div class="small-12 medium-4 columns presentation-cours-logo">
      <%= @course.course_icon %>
    </div>
    <!-- Fin Icone du cours -->

    <!-- Informations du cours -->
    <div class="small-12 medium-8 columns presentation-cours-info">
      <div class="presentation-cours-info-category"><%= @course.category %></div>
      <div class="presentation-cours-info-level right"><%= @course.level %></div>
      <h2 class="presentation-cours-info-title"><%= @course.title %></h2>
      <div class="presentation-cours-info-description"><%= @course.description %></div>   
      <%= link_to 'Voir Cours', @course, class: "button radius" %>
      <% if can? :edit, @course %>
        <%= link_to 'Modifier', '#', data: {:'reveal-id' => "EditCourse"}, class: "button small radius info" %>
      <% end %>
      <% if can? :destroy, @course %>
        <%= link_to 'Supprimer', @course, class: "button small radius alert", method: :delete, data: { confirm: 'Confirmer?' } %>
      <% end %>
    </div>
    <!-- Fin Informations du cours -->

    <!-- Bloc Progression du cours -->
    <div class="small-12 columns progression">
        <div class="row">
          
          <!-- Ligne Bar de Progression -->
          <div class="small-12 medium-10 columns">
            <div class="progress small-12 success round">
              <span class="meter" style="width: 15%"></span>
            </div>
          </div>
          <!-- Fin Ligne Bar de Progression -->

          <!-- Pourcentage Terminé -->
          <div class="small-12 medium-2 columns">
            <span class="subheader">15% Progression</span>
          </div>
          <!-- Fin Pourcentage Terminé -->

        </div>     
    </div>
    <!-- Fin Bloc Progression du cours -->

  </div>
  <!-- Fin Bloc de Présentation Générale du Cours -->

  <!-- Détails du Cours -->
  <div class="row section-details-cours">

    <!-- Section Gauche : Listing des chapitres et Lecons -->
    <div class="small-12 medium-9 columns section-details-cours-gauche">

      <!-- Nombre d'étapes -->
      <div class="subheader">
        Nombres d'étapes / Durée
      </div>
      <!-- Fin Nombre d'étapes -->

      <div class="sortable">

      <!-- Listing des chapitres du cours -->
      <%@course.chapters.each do |chapter| %>

        <!-- Bloc d'un chapitre -->
        <div class="chapterlist-course panel-default" data-id="<%= chapter.id %>" style="cursor: move" data-course = "<%=@course.id%>">

          <div class="row chapter-bloc">

            <div class="small-12 medium-2 columns chapter-info-logo">
              <div>Img</div>
            </div>

            <div class="small-12 medium-10 columns">

              <div class="chapter-info-content">
                <div class="chapter-info-content-title"><%= chapter.title %></div>
                <div class="chapter-info-content-text">
                  <%= chapter.description %>
                  <div class="right">
                  <% if can? :edit, @course %>
                    <%= link_to '<i class="fi-pencil"></i>'.html_safe, edit_chapter_path(chapter), data: {:"reveal-id" => "myModal", :"reveal-ajax" => true} %>
                  <% end %>
                  <% if can? :destroy, @course %>
                    <%= link_to '<i class="fi-trash"></i>'.html_safe, chapter_path(chapter), method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </div>
                </div>
                

              </div>

            </div>

          </div>

          <!-- Bloc des lecons du chapitre -->
          <div class="lessonlist-bloc">
          
            <!-- Listing des lecons d'un chapitre -->
            <% chapter.lessons.each do |lesson| %>
            
              <!-- Ligne d'une lecon -->
              <%= link_to lesson do %>

                <div class="lessonline">

                  <div class="lessonstatus"><i class="fi-play-circle"></i></div>
                  <div class="lessontitle"><%= lesson.title %></div>
                  <div class="right">
                    <% if can? :edit, @course %>
                      <%= link_to '<i class="fi-pencil"></i>'.html_safe, edit_lesson_path(lesson), data: {:"reveal-id" => "myModal", :"reveal-ajax" => true} %>
                    <% end %>
                    <% if can? :destroy, @course %>
                      <%= link_to '<i class="fi-trash"></i>'.html_safe, lesson_path(lesson), method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </div>

                </div>

              <% end %>
              <!-- Fin Ligne d'une lecon -->

            <% end %>
            <!-- Fin Listing des lecons d'un chapitre -->

            <!-- Ajout Leçon -->
            <div class="lessonline">

              <div class="lessonstatus"><i class="fi-plus"></i></div>
              <div class="lessontitle">
                <%= link_to 'Nouvelle Leçon', new_chapter_lesson_path(chapter) , data: {:"reveal-id" => "myModal", :"reveal-ajax" => true} %>
              </div>

            </div>
            <!-- Fin Ajout Leçon -->

          </div>
          <!-- Fin Bloc des lecons d'un chapitre -->
          
        </div>
        <!-- Fin Bloc d'un chapitre -->

      <% end %>
      <!-- Fin Listing des chapitres -->

    </div>

      <!-- Bloc Nouveau Chapitre -->
      <div class="chapterlist-course">

        <div class="row chapter-bloc">

          <div class="chapter-info-content">
            <div class="chapter-info-content-title">
              <%= link_to "Nouveau Chapitre", new_course_chapter_path(@course) , data: {:"reveal-id" => "myModal", :"reveal-ajax" => true} %>
            </div>
          </div>

        </div>

      </div>
      <!-- End Bloc Nouveau Chapitre -->

    </div>
    <!-- Fin Section Gauche -->

    <!-- Section Droite : Professeur et Compétences apprises du cours + Administration -->
    <div class="small-12 medium-3 columns section-details-cours-droite">

      <!-- Bloc Professeur -->
      <div class="professeur-bloc">
        <div class="subheader">Professeur</div>

        <div class="professeur-info">
          <img src="<%= asset_path('brouchey.jpg') %>"/>
          <span><%= @course.teacher %></span>
          <p class="text-left">Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur</p>
        </div>
      </div>
      <!-- Fin Bloc Professeur -->

      <!-- Bloc Competences -->
      <div class="skills-bloc">
        <div class="subheader">Competences apprises</div>
        <div class="button round"><%= @course.learning_skills %></div>
      </div>
      <!-- Fin Bloc Competences -->

      <!-- Bloc Administration -->
      <div class="admin-bloc">

        <% if can? :edit, @course %>
          <div class="subheader">
            <div>Administration</div>
          </div>
          <%= link_to 'Modifier', '#', data: {:'reveal-id' => "EditCourse"}, class: "button small radius info" %>
        <% end %>

        <% if can? :destroy, @course %>
          <%= link_to 'Supprimer', @course, class: "button small radius alert", method: :delete, data: { confirm: 'Confirmer?' } %>
        <% end %>

      </div>
      <!-- Fin Bloc Administration -->

    </div>
    <!-- Fin Section Droite : Professeur et Compétences apprises du cours + Administration -->

  </div>
  <!-- Fin Détails du Cours -->  
       
  <!-- Modaux Invisibles -->
  <div id="myModal" class="reveal-modal" data-reveal>
    <!-- méthode modal sans lien commune à tout le monde, voir si l'on peut faire quelque chose de plus dry -->
  </div>

  <div id="EditCourse" class="reveal-modal" data-reveal>
    <!-- modal modification cours -->
    <%= render 'form' %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
  <!-- Fin Modaux Invisibles -->

</div>

app/views/courses/index.html.erb
<div class="library-content">

  <!-- Tête d'Affiche -->
  <div class="feature-course">

    <div class="row">

      <!-- Récuperation Objet du dernier Cours ajouté -->
      <% lastcourse = courses.last %>
      <!-- Fin Récuperation -->

      <!-- Affichage dernier Cours -->
      <div class="small-12 medium-3 columns hero-course-logo">
        <h3><i class="fi-html5"></i></h3>
      </div>

      <div class="small-12 medium-9 columns">

        <div class="hero-course-description">
          <h3 class="hero-course-description-title text-left"><%= lastcourse.title %></h3>
          <div class="hero-course-description-text text-left"><%= lastcourse.description %></div>
          <%= link_to 'Démarrer', lastcourse, class: "button radius success" %>
        </div>
      </div>
      <!-- Fin Affichage dernier Cours -->

    </div>
  </div>
  <!-- Fin Tête d'Affiche -->

  <!-- Reste Contenu de Page -->
  <div class="courselist-container">

    <!-- Bloc de Recherche -->
    <div class="row">
      <div class="small-12 medium-8 large-8 small-centered columns">
        <form>
            <label>Rechercher :
              <input type="text" placeholder="ex: HTML, Swift, Ruby...">
            </label>
        </form>
      </div>
    </div>
    <!-- Fin Bloc de Recherche -->

    <!-- Bloc Listing des Cours-->
    <div class="row">

      <!-- Affichage automatique de tous les Cours -->
      <% courses.each do |course| %>

        <div class="small-12 medium-6 large-4 columns left">

          <%= link_to course do %>

            <div class="course-card">

              <div class="course-card-banner">
                <span class="left"><%= course.level %></span>
                <span class="right">Durée</span>
              </div>

              <div class="course-card-block">

                <div><%= course.title %></div>
                <div><%= course.description %></div>
                <div><%= course.level %></div>
                <div><%= course.teacher %></div>
                <div><%= course.learning_skills %></div>
                <div><%= course.course_points %></div>
                <ul class="button-group">
                  <li><%= link_to 'Démarrer', course, class: "button small radius success" %></li>
                  <% if can? :update, @course %>
                    <li><%= link_to 'Editer', edit_course_path(course), class: "button small radius info" %></li>
                  <% end %>
                  <% if can? :destroy, @course %>
                    <li><%= link_to 'Détruire', course, class: "button small radius alert", method: :delete, data: { confirm: 'Confirmer?' } %></li>
                  <% end %>
                </ul>
              </div>

            </div>

          <% end %>

        </div>        

      <% end %>
      <!-- Fin Affichage automatique de tous les Cours -->

    </div>
    <!-- Fin Bloc Listing des Cours -->
    
    <!-- Si peut créer un cours, Affichage de Blocs Supplémentaires -->
    <% if can? :create, @course %>

      <div class="row">

        <!-- Bloc Création Cours -->
        <div class="small-12 small-centered medium-10 large-8 columns panel callout radius">
          <span>Gestion des Cours :</span>
          <ul>
            <li><%= link_to 'Ajouter un Cours', new_course_path %></li>
          </ul>
        </div>
        <!-- Fin Bloc Création Cours -->

        <!-- Bloc Affichage des Admins -->
        <div class="small-12 small-centered medium-10 large-8 columns panel callout radius">
          <span>Liste des Admins :</span>
          <ul>
            <% (User.with_role :admin).each do |user|%>
              <li><%= user.username %></li>
            <% end%>
          </ul>
        </div>
        <!-- Fin Bloc Affichage des Admins -->

      </div>
      
    <% end %>
    <!-- Fin Affichage Affichage de Blocs Supplémentaires -->

  </div>
  <!-- Fin Reste Contenu de Page -->

</div>

app/views/courses/new.html.erb
<div class="row">

	<h1>New Course</h1>
	<%= render 'form' %>
	<%= link_to 'Back', courses_path %>

</div>

app/views/courses/show.html.erb
<div class="course-content">

  <!-- Lien Retour -->
  <div class="row">
    <!-- link_to '<i class="fi-arrow-left"></i> Retour'.html_safe, url_for(:back) -->
    <%= link_to '<i class="fi-arrow-left"></i> Retour Librairie'.html_safe, courses_path %>
  </div>
  <!-- Fin Lien Retour -->

  <!-- Bloc de Présentation Générale du Cours -->
  <div class="row presentation-cours-bloc">

    <!-- Icone du cours -->
    <div class="small-12 medium-4 columns presentation-cours-logo">
      <%= @course.course_icon %>
    </div>
    <!-- Fin Icone du cours -->

    <!-- Informations du cours -->
    <div class="small-12 medium-8 columns presentation-cours-info">
      <div class="presentation-cours-info-category"><%= @course.category %></div>
      <div class="presentation-cours-info-level right"><%= @course.level %></div>
      <h2 class="presentation-cours-info-title"><%= @course.title %></h2>
      <div class="presentation-cours-info-description"><%= @course.description %></div>   
      <div class="button radius success">Démarrer</div>
      <% if can? :edit, @course %>
        <%= link_to 'Edition', edit_course_path(@course), class: "button radius info" %>
      <% end %>
    </div>
    <!-- Fin Informations du cours -->

    <!-- Bloc Progression du cours -->
    <div class="small-12 columns progression">
        <div class="row">
          
          <!-- Ligne Bar de Progression -->
          <div class="small-12 medium-10 columns">
            <div class="progress small-12 success round">
              <span class="meter" style="width: 15%"></span>
            </div>
          </div>
          <!-- Fin Ligne Bar de Progression -->

          <!-- Pourcentage Terminé -->
          <div class="small-12 medium-2 columns">
            <span class="subheader">15% Progression</span>
          </div>
          <!-- Fin Pourcentage Terminé -->

        </div>     
    </div>
    <!-- Fin Bloc Progression du cours -->

  </div>
  <!-- Fin Bloc de Présentation Générale du Cours -->

  <!-- Détails du Cours -->
  <div class="row section-details-cours">

    <!-- Section Gauche : Listing des chapitres et Lecons -->
    <div class="small-12 medium-9 columns section-details-cours-gauche">

      <!-- Nombre d'étapes -->
      <div class="subheader">
        Nombres d'étapes / Durée
      </div>
      <!-- Fin Nombre d'étapes -->

      <!-- Listing des chapitres du cours -->
      <%@course.chapters.each do |chapter| %>

        <!-- Bloc d'un chapitre -->
        <div class="chapterlist-course">

          <div class="row chapter-bloc">

            <div class="small-12 medium-2 columns chapter-info-logo">
              <div>Img</div>
            </div>

            <div class="small-12 medium-10 columns">

              <div class="chapter-info-content">
                <div class="chapter-info-content-title"><%= chapter.title %></div>
                <div class="chapter-info-content-text"><%= chapter.description %></div>
              </div>

            </div>

          </div>

          <!-- Bloc des lecons du chapitre -->
          <div class="lessonlist-bloc">
          
            <!-- Listing des lecons d'un chapitre -->
            <% chapter.lessons.each do |lesson| %>
            
              <!-- Ligne d'une lecon -->
              <%= link_to lesson do %>

                <div class="lessonline">

                  <div class="lessonstatus"><i class="fi-play-circle"></i></div>
                  <div class="lessontitle"><%= lesson.title %></div>
                  <div class="right">Status</div>

                </div>

              <% end %>
              <!-- Fin Ligne d'une lecon -->

            <% end %>
            <!-- Fin Listing des lecons d'un chapitre -->

          </div>
          <!-- Fin Bloc des lecons d'un chapitre -->
          
        </div>
        <!-- Fin Bloc d'un chapitre -->

      <% end %>
      <!-- Fin Listing des chapitres -->

    </div>
    <!-- Fin Section Gauche -->

    <!-- Section Droite : Professeur et Compétences apprises du cours + Administration -->
    <div class="small-12 medium-3 columns section-details-cours-droite">

      <!-- Bloc Professeur -->
      <div class="professeur-bloc">
        <div class="subheader">Professeur</div>

        <div class="professeur-info">
          <img src="<%= asset_path('brouchey.jpg') %>"/>
          <span><%= @course.teacher %></span>
          <p class="text-left">Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur Description Professeur</p>
        </div>
      </div>
      <!-- Fin Bloc Professeur -->

      <!-- Bloc Competences -->
      <div class="skills-bloc">
        <div class="subheader">Competences apprises</div>
        <div class="button round"><%= @course.learning_skills %></div>
      </div>
      <!-- Fin Bloc Competences -->

      <!-- Bloc Administration -->
      <div class="admin-bloc">

        <% if can? :edit, @course %>
          <div class="subheader">
            <div>Administration</div>
          </div>
          <%= link_to 'Edition', edit_course_path(@course), class: "button small radius info" %>
        <% end %>

        <% if can? :destroy, @course %>
          <%= link_to 'Supprimer', @course, class: "button small radius alert", method: :delete, data: { confirm: 'Confirmer?' } %>
        <% end %>

      </div>
      <!-- Fin Bloc Administration -->

    </div>
    <!-- Fin Section Droite : Professeur et Compétences apprises du cours + Administration -->

  </div>
  <!-- Fin Détails du Cours -->  

</div>