config/routes.rb
Rails.application.routes.draw do



 devise_scope :user do
    get "welcome/:page" => "welcome#show", :as => 'welcome'

  unauthenticated  do
    root "welcome#home", as: :unauthenticated_root
  end
  authenticated do
    get "dashboard/:page" => "dashboard#show", :as => 'dashboard'
    root 'dashboard#dashboard', as: :authenticated_root
  end
  # get 'user/:username' => 'user#profile'
 end


devise_for :users, controllers: {
        sessions: 'users/sessions'
      }



get 'welcome/home'
get 'welcome/contact'
# get '/:username' => 'dashboard#profile'

# Ressources users || particulièrment dangereux
# doit etre changer pour seulement si super admin et faire un crud pour chaque utilisateur
# Proteger par un double mot de passe
# et doit etre une suppression soft / grosse suppression doit uniquement etre faire via console
# et demande ecrite de l utilisateur
# resources :users, :path => '', :only => [:show]
  resources :users

# devise_for :user 
# two lines below are needed for devise/controller
 
    

  scope shallow_path: "librairie" do
    resources :courses, :path => "librairie" do
    	resources :chapters, shallow: true
      put :edit, on: :member  
    end


    resources :chapters do 
        resources :lessons, shallow: true
    end
    resources :lessons

  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
belongs_to :course
has_many :lessons

# acts_as_list :scope => :course

default_scope { order("position ASC") }
	
	
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  # before_action :set_chapter, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!


     # @chapter = Chapter.find(params[:id])
# layout false

def index
    # @chapter = Chapter.find(params[:id])
    # @course = @chapter.course
     @course = Course.find(params[:course_id])
     @chapters = @course.chapters.all
 end


# GET /chapters/1
  # GET /chapters/1.json
  # def show
  # end

  # GET /chapters/new
  def new

    @course = Course.find(params[:course_id])
    @chapter = @course.chapters.new
    # code below remove layout from modal
    respond_to do |format|
         format.html {render :layout => false} #add this line.
   end
  end


 #  def sort
 #    @course = Course.find(params[:course_id])
 #    if request.get?
 #      # @course = Course.find(params[:course_id])
 #      @chapters = @course.chapters
 # elsif request.post?
 #      @chapter = Chapter.find(params[:chapter_id])
 #      params[:order].each do |key,value|
 #      @chapter.update_attribute(:chapter_id,value[:position])
 #    end
 #    render :nothing => true
 #  end
 #  end



  # GET /chapters/1/edit
  def edit

    @chapter = Chapter.find(params[:id])
    @course = @chapter.course
    # @course = Course.find(params[:course_id])
    # @chapter = @course.chapters.find(params[:id])
    respond_to do |format|
         format.html {render :layout => false} 
         # add this line.
   end
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @course = Course.find(params[:course_id])
    @chapter = @course.chapters.new(chapter_params)
    # respond_modal_with @chapter, location: root_path

  if @chapter.save
    flash[:success] = "ajout d'un chapitre"
    redirect_to edit_course_path(@course)
  else
    flash[:error] = "probleme d'ajout d'un chapitre"
    render action: :new
    redirect_to edit_course_path(@course)
  end
end




  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    @chapter = Chapter.find(params[:id])
    @course = @chapter.course
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to edit_course_path(@course), notice: 'chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    @course = @chapter.course
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to edit_course_path(@course), notice: 'chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


# Never trust parameters from the scary internet, only allow the white list through.
    private
    def chapter_params
      params.require(:chapter).permit(:id, :title, :description, :logo, :points, :position)
    end
end 




  #   respond_to do |format|
  #     if @chapter.save
  #       format.html { redirect_to @chapter, notice: 'chapter was successfully created.' }
  #       format.json { render :show, status: :created, location: @chapter }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @chapter.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  # private
    # Use callbacks to share common setup or constraints between actions.
    # def set_chapter
    #   @chapter = chapter.find(params[:id])
    # end

    

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= simple_form_for([@course, @chapter]) do |f| %>

  <%= f.label :id %>
  <%= f.text_field :id %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "Save" %>
<% end %>

app/views/chapters/_new.html.erb
<h1>Nouveau Chapitre</h1>

<%= render 'form' %>

app/views/chapters/edit.html.erb
<h1>Editing Chapters</h1>

<%= simple_form_for(@chapter) do |f| %>

  <%= f.label :id %>
  <%= f.text_field :id %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "Save" %>
<% end %>


<a class="close-reveal-modal">&#215;</a>

app/views/chapters/index.html.erb
<%= link_to '<i class="fi-arrow-left"></i> librairie'.html_safe, courses_path() %>
<h1><%=@course.title%></h1>
<h1><%= 'Description du cours :' + "  "+ @course.description%></h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Modules</th>
      <th>Description</th>
      <th>course_icon</th>
      <th>Category</th>
      <th>Level</th>
      <th>Teacher</th>
      <th>Learning skills</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%  @course.chapters.each do |chapter| %>
            <tr>

        <td><%= chapter.chapter_id %></td>
        <td><%= chapter.title %></td>
        <td> <%=link_to "lessons", chapter_lessons_path(chapter) %>  </td>
                <td> <%=link_to "sort", chapter_sort_path(chapter) %>  </td>

        <td><%= chapter.description %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<%  @course.chapters.each do |chapter| %>
<br> <br><br> <br><br> <br>
 <%= "titre du chapitre est : " + chapter.title%>
<%  chapter.lessons.each do |lesson| %>
<br>
 <%= "titre de la lecon est : " + lesson.title %>
    <% end %>
    <% end %>
<br> <br><br> <br>
<%= link_to 'New chapter', new_course_chapter_path %>

app/views/chapters/new.html.erb
<h1>Nouveau Chapitre</h1>

<%= render 'form' %>

<a class="close-reveal-modal">&#215;</a>