config/routes.rb
Rails.application.routes.draw do



 devise_scope :user do
    get "welcome/:page" => "welcome#show", :as => 'welcome'

  unauthenticated  do
    root "welcome#home", as: :unauthenticated_root
  end
  authenticated do
    get "dashboard/:page" => "dashboard#show", :as => 'dashboard'
    root 'dashboard#dashboard', as: :authenticated_root
  end
  # get 'user/:username' => 'user#profile'
 end


devise_for :users, controllers: {
        sessions: 'users/sessions'
      }



get 'welcome/home'
get 'welcome/contact'
# get '/:username' => 'dashboard#profile'

# Ressources users || particulièrment dangereux
# doit etre changer pour seulement si super admin et faire un crud pour chaque utilisateur
# Proteger par un double mot de passe
# et doit etre une suppression soft / grosse suppression doit uniquement etre faire via console
# et demande ecrite de l utilisateur
# resources :users, :path => '', :only => [:show]
  resources :users

# devise_for :user 
# two lines below are needed for devise/controller
 
    

  scope shallow_path: "librairie" do
    resources :courses, :path => "librairie" do
    	resources :chapters, shallow: true
      put :edit, on: :member  
    end


    resources :chapters do 
        resources :lessons, shallow: true
    end
    resources :lessons

  end

end

app/views/layouts/_dashboard_nav.erb
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false">
  <ul class="title-area">
    <li class="name left-off-canvas-toggle">
      <h1><a href="#"><i class="fi-list"></i><span>Pylon</span></a></h1>
    </li>
    <!-- For Responsive design on smaller devices : -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone. -->
  </ul>

  <section class="top-bar-section">
    <!-- Right Navigation Links -->
    <ul class="right">
      <li class="divider"></li>
      <li><a href="#"><i class="fi-trophy"></i><span>Points<span></a></li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="#"><i class="fi-torso"></i><span>Profile<span></a>
        <ul class="dropdown">
          <li><a href="#">Compte</a></li>
          <li><a href="#">Reglages</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li><a href="#"><i class="fi-comments"></i><span>Alertes<span></a></li>
      <li class="divider"></li>
      <li><%= link_to('Déconnexion', destroy_user_session_path, :method => :delete) %></li>
    </ul>
    <!-- End Right Navigation Links -->
  </section>
</nav>

app/views/layouts/_dashboard_nav.html.erb
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Pylon</a></h1>
    </li>
    <!-- For Responsive design on smaller devices : -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone. -->
  </ul>

  <section class="top-bar-section">
  
    <!-- Middle Navigation Links -->
    <ul class="middle">
      <li><a href="#"><i class="fi-trophy"></i><span>Rang<span></a></li>
      <li class="divider"></li>
      <li>
        <%= link_to dashboard_path('profile') do %>
          <%= image_tag(current_user.avatar.thumb.url) %>
          <span><%= current_user.username %></span>
        <% end %>
      </li>
      <li class="divider"></li>
      <li><a href="#"><i class="fi-comments"></i><span>Alertes<span></a></li>
    </ul>
    <!-- End Middle Navigation Links -->

    <!-- End Right Navigation Links -->
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to('<i class="fi-power"></i>'.html_safe, destroy_user_session_path, :method => :delete) %></li>
    </ul>
    <!-- End Right Navigation Links -->

  </section>
</nav>

app/views/layouts/_home_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Pylon', unauthenticated_root_path %></h1>
    </li>
    <!-- For Responsive design on smaller devices : -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone. -->
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
	    <li><a href="#">Fonctionnalités</a></li>
	    <li><a href="#">Abonnement</a></li>
	    <li><%= link_to 'Connexion', '#', data: {:'reveal-id' => "signupModal"} %></li>
		<li><%= link_to('Inscription', new_user_registration_path) %></li>
    </ul>
  </section>
</nav>

app/views/layouts/_left_sidebar.html.erb
<div class="left-sidebar">
  <ul class="propreties-sidebar">

    <li><%= link_to '<i class="fi-home"></i>Portail'.html_safe, authenticated_root_path %></li>
    <li><%= link_to '<i class="fi-database"></i>Librairie'.html_safe, courses_path%></li>
    <li><a href="#"><i class="fi-star"></i>Favoris</a></li>
    <li><a href="#"><i class="fi-target"></i>Objectifs</a></li>
    <li><a href="#"><i class="fi-trophy"></i>Rang</a></li>
    <li><a href="#"><i class="fi-graph-bar"></i>Stats</a></li>
    <li><a href="#"><i class="fi-comments"></i>Forum</a></li>
    <li><a href="#"><i class="fi-wrench"></i>Admin</a></li>
    <li class="toggleSidebar"><a href="#"><i class="fi-arrow-left"></i>Fermer</a></li>
  </ul>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
	    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
	      <%= content_tag :div, msg %>
	      <a href="#" class="close">&times;</a>
	    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pylon" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pylon" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>   
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%if user_signed_in? %>

    <!-- User (if logged in) = Dashboard Topbar + Left Sidebar Menu -->

    <!-- Dashboard Topbar -->
    <div class="fixed">
      <%= render 'layouts/dashboard_nav' %>
    </div>
    <!-- End Topbar -->

    <!-- Main Content = Left Sidebar + Page Content -->
    <div class="main-container">

      <!-- Left Sidebar -->
      <%= render 'layouts/left_sidebar' %>
      <!-- End Left Sidebar -->

      <!-- Page Content -->
      <div class="render-page">
        <%= yield %>
      </div>
      <!-- End Page Content -->

    </div>
    <!-- End Main Content -->

    <% else %>
    
      <!-- Visitor (not logged in) = Simple Fixed Home Topbar -->
      <div class="contain-to-grid fixed">
        <%= render 'layouts/home_nav' %>
      </div>
      <!-- End Topbar -->

      <!-- Main Content -->
      <%= render 'layouts/messages' %>
      <%= yield %>
      <!-- End Main content -->

      <!-- Invisible signupModal -->
      <div id="modal-holder"></div>

      <div id="signupModal" class="reveal-modal" data-reveal>
        <%= render 'users/sessions/new' %>
        <a class="close-reveal-modal">&#215;</a>
      </div>
      <!-- End Invisible signupModal -->

    <% end %>
 
  </body>
</html>